require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'test/dummy/db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'test/dummy/bin/**/*'

Metrics/LineLength:
  Max: 100

Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - test/dummy/config/**/*
    - spec/**/*
    - test/dummy/spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
    - test/dummy/spec/**/*

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false