version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3-node-browsers
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Update system gems
          command: |
            sudo gem update --system
      - run:
          name: Update Bundler
          command: |
            gem install bundler:2.2.17
      - run: # Install Ruby dependencies
          name: Bundle Install
          command: |
            bundle install
      # Database setup
      - run: bin/rails db:create
      - run: bin/rails db:migrate

      # run tests!
      - run:
          name: RSpec Unit Tests
          command: |
            rspec --format documentation spec/


